"""
Mostly copy-paste from timm library.
https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/vision_transformer.py
https://raw.githubusercontent.com/facebookresearch/dino/refs/heads/main/vision_transformer.py
"""
import math
import numpy as np
from functools import partial

import torch
import torch.nn as nn

from utils.popart import PopArt
from utils.rope import RotaryPositionalEmbeddings as RoPE
from utils.seq_running_mean_std import SeqRunningMeanStd

def cosine_scheduler(base_value, final_value, epochs, niter_per_ep, warmup_epochs=0, start_warmup_value=0):
    warmup_schedule = np.array([])
    warmup_iters = warmup_epochs * niter_per_ep
    if warmup_epochs > 0:
        warmup_schedule = np.linspace(start_warmup_value, base_value, warmup_iters)

    iters = np.arange(epochs * niter_per_ep - warmup_iters)
    schedule = final_value + 0.5 * (base_value - final_value) * (1 + np.cos(np.pi * iters / len(iters)))

    schedule = np.concatenate((warmup_schedule, schedule))
    assert len(schedule) == epochs * niter_per_ep
    return schedule

def clip_gradients(model, clip):
    norms = []
    for name, p in model.named_parameters():
        if p.grad is not None:
            param_norm = p.grad.data.norm(2)
            norms.append(param_norm.item())
            clip_coef = clip / (param_norm + 1e-6)
            if clip_coef < 1:
                p.grad.data.mul_(clip_coef)
    return norms

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def drop_path(x, drop_prob: float = 0., training: bool = False):
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

        # causal mask to ensure that attention is only applied to the left in the input sequence
        # self.register_buffer("mask", torch.tril(torch.ones(dim, dim)).view(1, 1, dim, dim))

        self.k_cache = None
        self.v_cache = None

        # trunc_normal_(self.pos_embed_param, std=.02)

    def forward(self, x, seq_id, seq_tel=None, seq_ttg=None, rope_proj=None, pos_proj=None, is_causal=False, attn_mask=None, use_kv_cache=False):
        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]

        if rope_proj is not None:
            # RoPE takes [b, s, n_h, h_d] as input: 
            #             b: batch size
            #             s: sequence length
            #             n_h: num heads
            #             h_d: head dim
            # q, k, v takes the shape of [b, n_h, s, h_d]
            # apply rotary positional encoding to q & k only: 
            # https://github.com/meta-llama/llama/blob/main/llama/model.py#L280

            if is_causal:
                assert seq_tel is not None
                q = torch.transpose(rope_proj(torch.transpose(q, 1, 2), input_pos=seq_tel), 1, 2) # [b, n_h, s, h_d]
                k = torch.transpose(rope_proj(torch.transpose(k, 1, 2), input_pos=seq_tel), 1, 2) # [b, n_h, s, h_d]
            else:
                assert seq_ttg is not None
                q = torch.transpose(rope_proj(torch.transpose(q, 1, 2), input_pos=seq_ttg), 1, 2) # [b, n_h, s, h_d]
                k = torch.transpose(rope_proj(torch.transpose(k, 1, 2), input_pos=seq_ttg), 1, 2) # [b, n_h, s, h_d]

        elif pos_proj is not None:
            if is_causal:
                assert seq_tel is not None
                pos_emb = pos_proj(seq_tel).unsqueeze(1) # (B, N, head_dim)
            else:
                assert seq_ttg is not None
                pos_emb = pos_proj(seq_ttg).unsqueeze(1)

            # add positional encoding to q, k
            pos_qkv = self.qkv(pos_emb).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
            pos_q, pos_k = pos_qkv[0], pos_qkv[1]
            q = q + pos_q
            k = k + pos_k

            # add id encoding to q, k
            # id_emb = self.id_proj(seq_id).unsqueeze(1)
            # q = q + id_emb
            # k = k + id_emb

        if use_kv_cache:
            assert N == 1 # only support one-step prediction
            if self.k_cache is None or self.v_cache is None:
                self.k_cache, self.v_cache = k, v
            else:
                self.k_cache = torch.cat((self.k_cache, k), dim=-2)
                self.v_cache = torch.cat((self.v_cache, v), dim=-2)
                k, v = self.k_cache, self.v_cache 

        attn = (q @ k.transpose(-2, -1)) * self.scale

        # BUG: per-step attention only; equivalent to MLP
        # if not use_kv_cache:
        #     _mask = torch.tril(torch.ones_like(attn, dtype=torch.bool))
        #     _mask = _mask & torch.triu(torch.ones_like(attn, dtype=torch.bool))
        #     attn.masked_fill_(~_mask, float('-inf'))
        
        # if attn_mask is not None and is_causal:
        #     attn_mask = attn_mask.unsqueeze(1) # multihead
        #     attn.masked_fill_(~attn_mask, float('-inf'))

        if not use_kv_cache and is_causal: # if use kv cache, then it is a one-step causal prediction
            causal_mask = torch.tril(torch.ones_like(attn, dtype=torch.bool)) 
            attn.masked_fill_(~causal_mask, float('-inf'))
        # else: 
        #     noncausal_mask = torch.triu(torch.ones_like(attn, dtype=torch.bool))
        #     attn.masked_fill_(~noncausal_mask, float('-inf'))
        #     _mask = torch.tril(torch.ones_like(attn, dtype=torch.bool))
        #     _mask = _mask & torch.triu(torch.ones_like(attn, dtype=torch.bool))
        #     attn.masked_fill_(~_mask, float('-inf'))

        attn = attn.softmax(dim=-1)
        if not is_causal:
            attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x, attn


class Block(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop=0., attn_drop=0.,
                 drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = Attention(
            dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale, attn_drop=attn_drop, proj_drop=drop)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)

    def forward(self, x, seq_id, seq_tel=None, seq_ttg=None, is_causal=False, rope_proj=None, 
                pos_proj=None, attn_mask=None, use_kv_cache=False, return_attention=False):

        y, attn = self.attn(self.norm1(x), seq_id=seq_id, seq_tel=seq_tel, seq_ttg=seq_ttg, 
                            rope_proj=rope_proj, pos_proj=pos_proj, is_causal=is_causal, 
                            attn_mask=attn_mask, use_kv_cache=use_kv_cache)

        if return_attention:
            return attn
        x = x + self.drop_path(y)
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x

    def clear_cache(self):
        self.attn.k_cache = None
        self.attn.v_cache = None


class ObsEmbed(nn.Module):
    """ Obs to Embedding
    """
    def __init__(self, obs_dim, embed_dim=768):
        super().__init__()
        self.proj = nn.Linear(obs_dim, embed_dim, bias=False)

    def forward(self, x):
        x = self.proj(x)
        return x

LOG_STD_MAX = 2
LOG_STD_MIN = -2

class UniversalTransformer(nn.Module):
    def __init__(self, obs_size, seq_len, norm_obs=True, num_actions=None, dim_actions=None, obs_embed_fn=None, 
                 embed_dim=768, depth=12, num_heads=12, mlp_ratio=4., qkv_bias=False, 
                 qk_scale=None, drop_rate=0., attn_drop_rate=0., with_popart=False, decoder_critic=False, 
                 shared=True, use_rope=False, logstd_head=False, drop_path_rate=0., 
                 norm_layer=partial(nn.LayerNorm, eps=1e-6), timelimit=1000):

        super().__init__()
        self.num_features = self.embed_dim = embed_dim
        self.seq_len = seq_len
        self.with_popart = with_popart
        self.decoder_critic = decoder_critic
        self.shared = shared
        self.logstd_head = logstd_head

        # running mean std for observation normalization 
        self.obs_rms = SeqRunningMeanStd(obs_size) if norm_obs else None

        # self.pos_drop = nn.Dropout1d(p=drop_rate)
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule

        if self.shared:
            blocks = nn.ModuleList([
                Block(
                    dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale, 
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
                for i in range(depth)])
            norm = norm_layer(embed_dim)

            self.encoder_blocks = blocks
            self.decoder_blocks = blocks
            self.encoder_norm = norm
            self.decoder_norm = norm

        else:
            self.encoder_blocks = nn.ModuleList([
                Block(
                    dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale, 
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
                for i in range(depth)])
            self.encoder_norm = norm_layer(embed_dim)

            self.decoder_blocks = nn.ModuleList([
                Block(
                    dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale, 
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
                for i in range(depth)])
            self.decoder_norm = norm_layer(embed_dim)

        self.v_head = PopArt(embed_dim, 1, norm_axes=-1) if with_popart else nn.Linear(embed_dim, 1)

        self.is_discrete = num_actions is not None
        if num_actions is not None:
            self.pi_head = nn.Linear(embed_dim, num_actions)
        else: 
            assert dim_actions is not None
            self.pi_mean = nn.Linear(embed_dim, dim_actions)
            # log_std = -0.5 * np.ones(dim_actions, dtype=np.float32) # from https://github.com/openai/spinningup/blob/038665d62d569055401d91856abb287263096178/spinup/algos/pytorch/ppo/core.py#L84C10-L84C60
            # self.pi_logstd = nn.Parameter(torch.as_tensor(log_std))
            if logstd_head:
                self.pi_logstd = nn.Linear(embed_dim, dim_actions)
            else:
                self.pi_logstd = nn.Parameter(torch.zeros(1, dim_actions))

            self.is_discrete = False

            # https://openreview.net/pdf?id=nIAxjsniDzg
            # The key recipe is to initialize the policy at the beginning of training so that the action distribution is
            # centered around 0 regardless of the observation and has a rather small standard deviation
            # trunc_normal_(self.pi_mean.weight, std=.005)
            # nn.init.constant_(self.pi_mean.bias, 0)

        self.apply(self._init_weights)

        self.obs_embed = ObsEmbed(obs_dim=obs_size[0], embed_dim=embed_dim) if obs_embed_fn is None else obs_embed_fn
        # self.rew_proj = nn.Linear(1, embed_dim, bias=False)

        max_T = timelimit+1 # 1000 is the max time step in the environment; padding with 0; plus the final terminal state
        head_dim = embed_dim // num_heads
        self.use_rope = use_rope
        if self.use_rope:
            self.rope_proj = RoPE(dim=head_dim, max_seq_len=max_T)
            self.pos_proj = None
        else:
            self.pos_proj = nn.Embedding(max_T, embed_dim) # 0 is the padding index
            trunc_normal_(self.pos_proj.weight, std=.02)
            self.rope_proj = None

        self.id_proj = nn.Embedding(seq_len, embed_dim) 
        trunc_normal_(self.id_proj.weight, std=.02)
        # self.pos_embed_param = nn.Parameter(torch.zeros(1, seq_len, embed_dim)) 

        if self.logstd_head:
            # initialize weight & bias to 0
            nn.init.constant_(self.pi_logstd.weight, 0)
            nn.init.constant_(self.pi_logstd.bias, 0)
        # self.pos_idx = 0

        self.params_pi = list(self.obs_embed.parameters()) + list(self.id_proj.parameters()) + list(self.pos_proj.parameters()) + \
            list(self.decoder_blocks.parameters()) + list(self.decoder_norm.parameters()) + list(self.pi_mean.parameters()) + [self.pi_logstd]
        # self.params_pi = list(self.decoder_blocks.parameters()) + list(self.decoder_norm.parameters()) + list(self.pi_mean.parameters()) + [self.pi_logstd]

        # self.params_v = list(self.obs_embed.parameters()) + list(self.id_proj.parameters()) + list(self.pos_proj.parameters()) + \
        #     list(self.encoder_blocks.parameters()) + list(self.encoder_norm.parameters()) + list(self.v_head.parameters())
        self.params_v = list(self.encoder_blocks.parameters()) + list(self.encoder_norm.parameters()) + list(self.v_head.parameters())

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def joint_forward(self, seq_obs, seq_id, seq_tel, seq_ttg, attn_mask=None):
        embeds = self.obs_embed(seq_obs)  # linear embedding
        embeds += self.id_proj(seq_id)
        embeds += self.pos_proj(seq_tel)

        x_pi = embeds

        for blk in self.decoder_blocks:
            x_pi = blk(x_pi, seq_id=seq_id, seq_tel=seq_tel, is_causal=True, attn_mask=attn_mask)
        x_pi = self.decoder_norm(x_pi)

        if self.is_discrete:
            outputs = self.pi_head(x_pi)
        else:
            mean = self.pi_mean(x_pi)

            if self.logstd_head:
                logstd = self.pi_logstd(x_pi)
            else:
                logstd = self.pi_logstd.expand_as(mean)

            logstd = torch.clamp(logstd, LOG_STD_MIN, LOG_STD_MAX)
            outputs = torch.cat([mean, logstd], dim=-1)

        # val = self.v_head(x_pi)

        x_val = embeds
        # x_val = self.pos_drop(x_val)

        # seq_rew = torch.cat((seq_rew, torch.zeros_like(seq_rew[:, -1]).unsqueeze(-1)), dim=-1).unsqueeze(-1)
        # x_val = x_val + self.rew_proj(seq_rew)

        for blk in self.encoder_blocks:
            x_val = blk(x_val, seq_id=seq_id, seq_ttg=seq_ttg, is_causal=self.decoder_critic, attn_mask=attn_mask)
        x_val = self.encoder_norm(x_val)
        val = self.v_head(x_val)

        return outputs, val.squeeze(-1)

    def forward(self, seq_obs, seq_id, seq_tel, attn_mask=None, use_kv_cache=False):
        x = self.obs_embed(seq_obs)
        x += self.id_proj(seq_id)
        x += self.pos_proj(seq_tel)
        
        for blk in self.decoder_blocks:
            x = blk(x, seq_id=seq_id, seq_tel=seq_tel, is_causal=True, attn_mask=attn_mask, use_kv_cache=use_kv_cache) # use kv cache for faster inference
        x = self.decoder_norm(x)

        if self.is_discrete:
            outputs = self.pi_head(x)
        else:
            mean = self.pi_mean(x)

            if self.logstd_head:
                logstd = self.pi_logstd(x)
            else:
                logstd = self.pi_logstd.expand_as(mean)

            logstd = torch.clamp(logstd, LOG_STD_MIN, LOG_STD_MAX)
            outputs = torch.cat([mean, logstd], dim=-1)

        return outputs

    def clear_cache(self):
        for blk in self.decoder_blocks:
            blk.clear_cache()

    def forward_val(self, seq_obs, seq_id, seq_ttg, attn_mask=None):
        x = self.obs_embed(seq_obs)  # linear embedding
        x += self.id_proj(seq_id)
        x += self.pos_proj(seq_ttg)

        # seq_rew = torch.cat((seq_rew, torch.zeros_like(seq_rew[:, -1]).unsqueeze(-1)), dim=-1).unsqueeze(-1)
        # x = self.rew_proj(seq_rew) # add reward embedding
        
        # seq_rew = torch.cat((seq_rew, torch.zeros_like(seq_rew[:, -1]).unsqueeze(-1)), dim=-1).unsqueeze(-1)
        # x = x + self.rew_proj(seq_rew) # add reward embedding

        for blk in self.encoder_blocks:
            x = blk(x, seq_id=seq_id, seq_ttg=seq_ttg, is_causal=self.decoder_critic, attn_mask=attn_mask)
        x = self.encoder_norm(x)
        val = self.v_head(x)
        return val.squeeze(-1)
